# NumPy Array Dimensionality

In [1]:
import numpy as np

## Data Shape Defined

### Vectors
Vector == 1 dimensional array

![alt text](../../../.images/vector.png)

To define the shape of a vector in numpy, two dimensions are supplied to indicate the "direction" in which the data is oriented.

![alt text](../../../.images/vector2.png)

### Matrices
Matrix == 2 dimensional array

![alt text](../../../.images/matrix.png)

### Tensors
Tensor == 1...n dimensional array

While mathematically arrays and matrices are tensors, in data science tensor is commonly used as a general name for data shapes with 3 or more dimensions.

![alt text](../../../.images/tensor.png)

## Array Shape

The `shape` property of an array displays the shape of the array in the form of a tuple. The values are ordered by dimension, with the first integer being the first dimension and so on.

In [3]:
array = np.zeros((3,5))
print(array)
array.shape

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(3, 5)

A shape of (3,5) refers to 3 rows and 5 columns. For 2D arrays, it is still common to refer to these dimensions as rows and columns.

## Re-Shaping an Array

### Flattening An Array
It can often be beneficial to change the shape of an array to a 1D array to perform some form of operation on all arrays.

The `flatten()` method brings the multi-dimensional array into a flat, 1D array.

In [5]:
array = np.array([[1,2],[5,7],[6,6]])
array.flatten()

array([1, 2, 5, 7, 6, 6])

### Reshaping an Array
We can reshape - or rearrange - the values in the array to a new defined shape.

In [6]:
array.reshape((2,3))

array([[1, 2, 5],
       [7, 6, 6]])

Note: the new array shape must have the right number of elements to properly fill the new shape.

For example, our array cannot be reshaped to `(3,3)` because the array does not contain 9 _(3x3)_ elements.

In [7]:
array.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)