# NumPy Arrays

Can only contain a single data type. 

Where possible, numpy will attempt to coerce the "best" choice in the given dataset. This may not be what is intended, so it is best to be intentional.

https://numpy.org/doc/stable/reference/generated/numpy.array.html 

In [2]:
import numpy as np

## Creating Arrays

### 1D Arrays from Python Lists

In [5]:
python_list = [3,2,5,8,4,9,7,6,1]
array = np.array(python_list)
print(array)
type(array)

[3 2 5 8 4 9 7 6 1]


numpy.ndarray

### 2D Arrays from Python Lists

In [6]:
python_list_of_lists = [[3,2,5],
                        [9,7,1],
                        [4,3,6]]

np.array(python_list_of_lists)

array([[3, 2, 5],
       [9, 7, 1],
       [4, 3, 6]])

### Arrays from Scratch

#### np.zeros()

Creates an np array of the specified shape and populated with zeros.

In [7]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### np.random.random()

Creates an np array of the specified shape and populated with random float values.

In [8]:
np.random.random((2,4))

array([[0.63204367, 0.54725755, 0.7332821 , 0.82782584],
       [0.00677348, 0.22304269, 0.94709478, 0.00413199]])

#### np.arange()

Creates a 1D np array with evenly spaced values in a specified range with an optional step.

The start value can be omitted, the stop value may not. If three args are presented, the third value represents step.

Notice that the stop value is not included in the array.

In [9]:
np.arange(-3,4)

array([-3, -2, -1,  0,  1,  2,  3])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.arange(-3, 4, 3)

array([-3,  0,  3])