# NumPY Data Types

NumPy data types are more specific than python's. A full listing of them can be found at the documentation link below.

https://numpy.org/doc/stable/reference/routines.dtypes.html

This allows us to be more precise (and thus efficient) by declaring a specific size for memory storage, such as using int8 to represent numbers 0-9, for example.

The default numeric size is 64 bytes (presumably on 64-bit systems as with other languages).

The data type of the NumPy array is determined at array creation.

In [1]:
import numpy as np

## .dtype Attribute
The `.dtype` attribute indicates the data type of the array. Recall that NumPy arrays are homogenous or all the same type.

In [4]:
np.array([1.32, 5.78, 175.55]).dtype

dtype('float64')

## String Data
String data types work a little bit different from numeric types. NumPy presents the type using character encoding and max length.

In [5]:
np.array(["Introduction", "to", "NumPy"]).dtype

dtype('<U12')

In the example above, the data type in the array is a unicdoe strength of a length 12.

## Defining the Data Type
It is possible to define the data type at creation. This is done using the optional `dtype` argument.

In [7]:
np.array([1.32, 5.78, 175.55], dtype=np.float32).dtype

dtype('float32')

## Converting the Data Type
We can use the `astype()` method to convert an array from one type to another.

In [8]:
boolean_array = np.array([[True, False], [False, False]], dtype=np.bool_)
boolean_array.astype(np.int8)

array([[1, 0],
       [0, 0]], dtype=int8)

## Type Coercion
NumPy will cast the types of a python list into a single type if multiple types exist. For example:

* Adding a float to an array of integers will change all integers into floats
* Adding an integer to an array of booleans will change all booleans into integers

In [12]:
list = [True, "Boop", 42, 42.42]
print(np.array(list))
print(np.array(list).dtype) # yeah, yeah - not very efficient


['True' 'Boop' '42' '42.42']
<U32


In [13]:
list = [0, 42, 42.42]
print(np.array(list))
print(np.array(list).dtype) # yeah, yeah - not very efficient

[ 0.   42.   42.42]
float64


In [14]:
list = [True, False, 42]
print(np.array(list))
print(np.array(list).dtype) # yeah, yeah - not very efficient

[ 1  0 42]
int64
